### ISSUE TITLE
tqdm.auto does not work fine in Atom hydrogen

### ISSUE THREAD

**Issue by kamione** [neurostuff/NiMARE#481] opened 2021-04-02 10:00 UTC
## Summary

tqdm.auto progress bar does not update if the codes are running in a Atom IDE with hydrogen

## Additional details

- NiMARE version: 0.0.7

### What were you trying to do?
I tried to run:
```python
ale = nimare.meta.cbma.ALE()
res = ale.fit(dset)

corr = nimare.correct.FWECorrector(method="montecarlo", n_iters=10, n_cores=-1)
cres = corr.transform(ale.results)
```

### What actually happened?
This block of codes only produced:
```
INFO:nimare.correct:Using correction method implemented in Estimator: nimare.meta.cbma.ale.ALE.correct_fwe_montecarlo.
  0%|          | 0/10 [00:00<?, ?it/s]
INFO:nimare.meta.cbma.base:Using null distribution for voxel-level FWE correction.
```
The codes worked perfectly but the progress bar does not update if I work in a Atom IDE with hydrogen
## Reproducing the bug

```python
# This problem can be simply reproduced in a Atom IDE with hydrogen by:
import time
from tqdm.auto import tqdm

for _ in tqdm(range(10)):
    time.sleep(1)
    pass
```

**Comment by jdkent** [comment] 2021-04-03 05:09
Thanks for raising this issue, if the problem is primarily with `tqdm`, I encourage you to open an issue on their github page: https://github.com/tqdm/tqdm/issues, and we can bump the versions of `tqdm` NiMARE uses once `tqdm` has an appropriate fix.

**Comment by kamione** [comment] 2021-04-16 10:48
Thanks a lot. An new issue is created in the tqdm repo.

**Comment by tsalo** [comment] 2021-04-19 19:23
Awesome! I'll close this now, but if we end up having to update our requirements (especially add a minimum tqdm version), please feel free to comment here or open a new issue.

**Closed by tsalo** 2021-04-19 19:23 UTC
Labels: bug
